localdb:
    image: postgres:11.2
    ports:
      - "5432:5432"
    volumes:
      - ./db/dumps:/app-db-dumps
    environment:
      - POSTGRES_USER=taqtile
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=databoard_db
  
testdb:
    image: postgres:11.2
    ports:
      - "5433:5432"
    volumes:
      - ./db/dumps:/app-db-dumps
    environment:
      - POSTGRES_USER=taqtile
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=databoard_test_db