export const userSeeds = [
  {
    name: "admin",
    email: "admin@taqtile.com",
    password: "1234qwer",
    birthDate: "1980-01-23",
    
  },
  {
    name: "Martynas Maryam",
    email: "martynas.maryam@gmail.com",
    password: "em8en8u96nu92du9",
    birthDate: "1980-09-21",
  },
  {
    name: "Iiris Manahem",
    email: "iris.anahem@gmail.com",
    password: "zdt6zu9jcz0ahjq9",
    birthDate: "1980-12-30",
  },
  {
    name: "Pritha Mitya",
    email: "pritha.mitya@gmail.com",
    password: "fce0zfyj8t07jgzm",
    birthDate: "1981-08-15",
  },
  {
    name: "Judoc Enora",
    email: "judoc.enora@gmail.com",
    password: "1z0ou0w03pivz67z",
    birthDate: "1983-01-02",
  },
  {
    name: "Elly Max",
    email: "elly.max@gmail.com",
    password: "ypw880uwsa2y62j3",
    birthDate: "1996-01-15",
  },
  {
    name: "Addilyn Ierameel",
    email: "addilyn.ierameel@gmail.com",
    password: "uwfbyufrkjar3a3k",
    birthDate: "1991-11-10",
  },
  {
    name: "Margalita Saturninus",
    email: "margalita.saturninus@gmail.com",
    password: "chcsbcg44ld5lviy",
    birthDate: "1995-03-29",
  },
  {
    name: "Mikhail Lynna",
    email: "mikhail.lynna@gmail.com",
    password: "4r5wqnawqjb98jlk",
    birthDate: "1992-10-03",
  },
  {
    name: "Oleksandr Eilish",
    email: "oleksandr.eilish@gmail.com",
    password: "0hxn7waohfk9g7gu",
    birthDate: "1994-06-07",
  },
  {
    name: "Tarja Christie",
    email: "tarja.christie@gmail.com",
    password: "1v16x6u31isiek17",
    birthDate: "1995-09-23",
  },
  {
    name: "Timur Murtada",
    email: "timur.murtada@gmail.com",
    password: "nt7ng9wwdkv9u5x5",
    birthDate: "1997-07-29",
  },
  {
    name: "Ioann Nicolaus",
    email: "ioann.nicolaus@gmail.com",
    password: "1tfwmr4xaez48sqt",
    birthDate: "2000-08-05",
  },
  {
    name: "Sunil Kawisenhawe",
    email: "sunil.kawisenhawe@gmail.com",
    password: "4bexxaors8v05phy",
    birthDate: "1991-05-06",
  },
  {
    name: "Pisti Dabid",
    email: "pisti.dabid@gmail.com",
    password: "q5ugmvi02n6bd1zf",
    birthDate: "1989-10-07",
  },
  {
    name: "Shakti Shawna",
    email: "shakti.shawna@gmail.com",
    password: "g7dy8uqjaj6pvb6e",
    birthDate: "1987-05-06",
  },
  {
    name: "Hlengiwe Hermanus",
    email: "hlengiwe.hermanus@gmail.com",
    password: "gpo7xtv8bi0ttfg7",
    birthDate: "1998-02-20",
  },
  {
    name: "Krishna Laila",
    email: "krishna.laila@gmail.com",
    password: "cgc7omid505y2u6b",
    birthDate: "1988-06-07",
  },
  {
    name: "Eustorgius Jolanta",
    email: "eustorgius.jolanta@gmail.com",
    password: "7fvkzym0d3r1g8n0",
    birthDate: "1986-07-03",
  },
  {
    name: "Davida Dorris",
    email: "davida.dorris@gmail.com",
    password: "w51kx4i88tajwqpj",
    birthDate: "1985-12-15",
  },
  {
    name: "Burak Conchita",
    email: "burak.conchita@gmail.com",
    password: "me0k1rtx9gjvrqaj",
    birthDate: "1984-07-21",
  },
  {
    name: "Eric Catrina",
    email: "eric.catrina@gmail.com",
    password: "yavtpbw6qdpfry13",
    birthDate: "2000-10-24",
  },
  {
    name: "Harsha Detlef",
    email: "harsha.detlef@gmail.com",
    password: "12guyl6aytt00epy",
    birthDate: "2001-08-09",
  },
  {
    name: "Iona Ellen",
    email: "iona.ellen@gmail.com",
    password: "j78a6e3jygc7n3n4",
    birthDate: "2005-08-18",
  },
  {
    name: "Morwen Anwar",
    email: "morwen.anwar@gmail.com",
    password: "f4r1lhlkhgyijqin",
    birthDate: "2006-11-04",
  },
  {
    name: "2admin",
    email: "2admin@taqtile.com",
    password: "1234qwer",
    birthDate: "1980-01-23",
  },
  {
    name: "2Martynas Maryam",
    email: "2martynas.maryam@gmail.com",
    password: "em8en8u96nu92du9",
    birthDate: "1980-09-21",
  },
  {
    name: "2Iiris Manahem",
    email: "2iris.anahem@gmail.com",
    password: "zdt6zu9jcz0ahjq9",
    birthDate: "1980-12-30",
  },
  {
    name: "2Pritha Mitya",
    email: "2pritha.mitya@gmail.com",
    password: "fce0zfyj8t07jgzm",
    birthDate: "1981-08-15",
  },
  {
    name: "2Judoc Enora",
    email: "2judoc.enora@gmail.com",
    password: "1z0ou0w03pivz67z",
    birthDate: "1983-01-02",
  },
  {
    name: "2Elly Max",
    email: "2elly.max@gmail.com",
    password: "ypw880uwsa2y62j3",
    birthDate: "1996-01-15",
  },
  {
  name: "a",
  email: "a@a.com",
  password: "1234asfdf",
  birthDate: "2001-08-03",
  addresses: [
    {
      CEP: "02345678",
      street: "Rua dos bobos",
      streetNumber: 321,
      neighborhood: "Biscoito",
      city: "São Paulo",
      state: "São Paulo",
      complement: "asdasda",
    },
    {
      CEP: "12345678",
      street: "Rua Sei la",
      streetNumber: 123,
      neighborhood: "Bairro seila",
      city: "São Paulo",
      state: "São Paulo",
    },
  ],
  },
  {
    name: "2Margalita Saturninus",
    email: "2margalita.saturninus@gmail.com",
    password: "chcsbcg44ld5lviy",
    birthDate: "1995-03-29",
  },
  {
    name: "2Mikhail Lynna",
    email: "2mikhail.lynna@gmail.com",
    password: "4r5wqnawqjb98jlk",
    birthDate: "1992-10-03",
  },
  {
    name: "2Oleksandr Eilish",
    email: "2oleksandr.eilish@gmail.com",
    password: "0hxn7waohfk9g7gu",
    birthDate: "1994-06-07",
  },
  {
    name: "2Tarja Christie",
    email: "2tarja.christie@gmail.com",
    password: "1v16x6u31isiek17",
    birthDate: "1995-09-23",
  },
  {
    name: "2Timur Murtada",
    email: "2timur.murtada@gmail.com",
    password: "nt7ng9wwdkv9u5x5",
    birthDate: "1997-07-29",
  },
  {
    name: "2Ioann Nicolaus",
    email: "2ioann.nicolaus@gmail.com",
    password: "1tfwmr4xaez48sqt",
    birthDate: "2000-08-05",
  },
  {
    name: "2Sunil Kawisenhawe",
    email: "2sunil.kawisenhawe@gmail.com",
    password: "4bexxaors8v05phy",
    birthDate: "1991-05-06",
  },
  {
    name: "2Pisti Dabid",
    email: "2pisti.dabid@gmail.com",
    password: "q5ugmvi02n6bd1zf",
    birthDate: "1989-10-07",
  },
  {
    name: "2Shakti Shawna",
    email: "2shakti.shawna@gmail.com",
    password: "g7dy8uqjaj6pvb6e",
    birthDate: "1987-05-06",
  },
  {
    name: "2Hlengiwe Hermanus",
    email: "2hlengiwe.hermanus@gmail.com",
    password: "gpo7xtv8bi0ttfg7",
    birthDate: "1998-02-20",
  },
  {
    name: "2Krishna Laila",
    email: "2krishna.laila@gmail.com",
    password: "cgc7omid505y2u6b",
    birthDate: "1988-06-07",
  },
  {
    name: "2Eustorgius Jolanta",
    email: "2eustorgius.jolanta@gmail.com",
    password: "7fvkzym0d3r1g8n0",
    birthDate: "1986-07-03",
  },
  {
    name: "2Davida Dorris",
    email: "2davida.dorris@gmail.com",
    password: "w51kx4i88tajwqpj",
    birthDate: "1985-12-15",
  },
  {
    name: "2Burak Conchita",
    email: "2burak.conchita@gmail.com",
    password: "me0k1rtx9gjvrqaj",
    birthDate: "1984-07-21",
  },
  {
    name: "2Eric Catrina",
    email: "2eric.catrina@gmail.com",
    password: "yavtpbw6qdpfry13",
    birthDate: "2000-10-24",
  },
  {
    name: "2Harsha Detlef",
    email: "2harsha.detlef@gmail.com",
    password: "12guyl6aytt00epy",
    birthDate: "2001-08-09",
  },
  {
    name: "2Iona Ellen",
    email: "2iona.ellen@gmail.com",
    password: "j78a6e3jygc7n3n4",
    birthDate: "2005-08-18",
  },
  {
    name: "2Morwen Anwar",
    email: "2morwen.anwar@gmail.com",
    password: "f4r1lhlkhgyijqin",
    birthDate: "2006-11-04",
  },
];
